<?php
namespace app\index\controller;
use app\api\Category;
use app\api\Channel;

/**
 * Created by PhpStorm.
 * User: imdante
 * Date: 2016/11/30
 * Time: 12:20
 */
class Thinkphp extends Common {
    private $channel_id = 12;
    private $categoryRow =[];
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $channel = Channel::search_channel('id',$this->channel_id);
        $this->assign('channel',$channel);
    }

    public function index(){
        $this->category($this->channel_id);

        return $this->fetch();
    }

    public function category($typid){
        $data = Category::datalist();

        foreach ($data as $item=>$value){
            if($value['type'] == $typid){
                $this->categoryRow[] = $value;
            }
        }
        $this->assign('category',unlimitedForLevel($this->categoryRow));
    }
    public function lists(){
        return $this->fetch();
    }
}